jobs:

######################### NATIVE WAR CI/CD JOBS #########################

# runCLI job that deploys artifact in S3 to EC2 - TEST
  - name: demo_war_s3_test_deploy
    type: runCLI
    steps:
      - IN: demo_war_s3_file
      - IN: demo_war_s3_cls
      - IN: demo_war_s3_awscli
      - TASK:
        - script: echo "Latest build is in S3 at "$DEMO_WAR_S3_FILE_SOURCENAME/$DEMO_WAR_S3_FILE_VERSIONNAME
        - script: aws s3 cp s3://$DEMO_WAR_S3_FILE_SOURCENAME/$DEMO_WAR_S3_FILE_VERSIONNAME ~/HelloWorld.war
        - script: echo -e "$DEMO_WAR_S3_CLS_INTEGRATION_PRIVATEKEY" > ~/.ssh/ec2-node && sudo chmod 600 ~/.ssh/ec2-node && echo "identity file created"
        - script: scp -i ~/.ssh/ec2-node ~/HelloWorld.war shippable@ec2-54-173-201-230.compute-1.amazonaws.com:/opt/tomcat-test/webapps && echo "file deployed to Tomcat server - test instance"
        - script: echo -e "LATEST_TEST_DEPLOY=$DEMO_WAR_S3_FILE_VERSIONNAME" >> $DEMO_WAR_S3_TEST_DEPLOY_STATE/latest_test_deploy.env

# runCLI job that deploys artifact in S3 to EC2 - PROD
# based on previous deployment to TEST environment
  - name: demo_war_s3_prod_deploy
    type: runCLI
    steps:
      - IN: demo_war_s3_test_deploy
        switch: off
      - IN: demo_war_s3_file
      - IN: demo_war_s3_cls
      - IN: demo_war_s3_awscli
      - TASK:
        - script: source $DEMO_WAR_S3_TEST_DEPLOY_STATE/latest_test_deploy.env
        - script: echo "Latest test deployment is in S3 at "$DEMO_WAR_S3_FILE_SOURCENAME/$LATEST_TEST_DEPLOY
        - script: aws s3 cp s3://$DEMO_WAR_S3_FILE_SOURCENAME/$LATEST_TEST_DEPLOY ~/HelloWorld.war
        - script: echo -e "$DEMO_WAR_S3_CLS_INTEGRATION_PRIVATEKEY" > ~/.ssh/ec2-node && sudo chmod 600 ~/.ssh/ec2-node && echo "identity file created"
        - script: scp -i ~/.ssh/ec2-node ~/HelloWorld.war shippable@ec2-54-173-201-230.compute-1.amazonaws.com:/opt/tomcat-prod/webapps && echo "file deployed to Tomcat server - prod instance"
